### ISSUE TITLE
Don't use XDR if we have a same domain request on IE8/9

### ISSUE THREAD

**Issue by oparoz** [amvtek/EventSource#11]
One problem with XDR is that the response needs to be public (Access-Control-Allow-Origin *).

It would be great if the polyfill could detect when the request isn't cross-domain and use XHR instead, allowing it to be used on protected pages.

If auto-detection is too difficult or unwanted, allowing us to force XHR mode would be good enough.

**Comment by amvtek** [comment]
The reason XDR is used for IE8/IE9 is that it provides 'progress' events which we process to detect that a new EventSource message has been fully received.

Switching to IE8/IE9 XHR will leave us without any way to detect that messages have been received. The use of XDR to receives never ending response is the only fallback solution we are aware of on IE8/IE9.

There are unfortunately no client side solution around this XDR limitation. Switching to XHR on IE8/IE9 will prevent the EventSource to detect any message prior to connection end. If you need to process source not directly available on your application host , I would suggest to proxy those source with nginx so as from the view point of connecting clients the source will appear to be originating from your application host.

Bests,
AmvTek

**Comment by oparoz** [comment]
It's true that you have to wait for the end of the stream before being able to process anything... It works for my use case, because I receive parallel short streams containing 6 events and can then process them all at once, but it won't work for a ticker.
It's a shame that XDR only works for public pages, but that's how Microsoft wanted it to be.

Thanks for the detailed answer.
