### ISSUE TITLE
npm?

### ISSUE THREAD

**Issue by ericelliott** [amvtek/EventSource#8]
Is this published on npm? If it's not, it should be. Npm is the gold standard package repository for JavaScript. It's 5x larger than Bower (and growing faster than Bower), and it's commonly used for both server-side and browser code (among other things). Over 60% of npm modules work in the browser via tools like Browserify.

**Comment by amvtek** [comment]
Yes, we have the same feeling.
This is on the roadmap, we need to get familiar with the whereabouts of npm publication :)

**Comment by ericelliott** [comment]
It looks to me like you've already done almost everything that's required. Now you just need to make sure you have an npm account, and run the publish command. [Here are the instructions you need to follow.](https://gist.github.com/coolaj86/1318304)

When your account is set up, all that's left is this:

```
npm publish
```

**Comment by amvtek** [comment]
package has been published to npm as **eventsource-polyfill**
Some work has gone into making it compatible with **browserify**
We are quite green at this, let us know any problem you may have.
