### ISSUE TITLE
[FR] Support running multiple EventSource streams in parallel

### ISSUE THREAD

**Issue by oparoz** [amvtek/EventSource#9]
When using Internet Explorer 11, it seems that as soon as there is more than one EventSource object, no data is shown until the timeout is reached.
Could you confirm this?

The same code with native EventSource on Firefox and Chrome works just fine.

**Comment by amvtek** [comment]
Hum, until now we have not used multiple EventSource on the same page. 

However if our polyfill does not support this, there is a problem. Can you pass us some example source code showing what you are trying to do.

**Comment by oparoz** [comment]
Sure, you can take a look at how your polyfill is used here: https://github.com/interfasys/galleryplus/blob/master/js/eventsource.js

**Comment by amvtek** [comment]
OK, we have a few questions
1. Could it be that the server you are connecting to can be silent for more than 5 minutes ? If this is the case the polyfill EventSource will timeout. You may modify this by changing the silentTimeout option to null, undefined or 0 to disable it or adjust to something longer eg 600000 ms for 10 mn silentTimeout.
2. Could it be that the server you are connecting to is sensitive to unexpected GET arguments in which case you may disable transmission of additional GET arguments by setting option getArgs to undefined.
3. Can you try to set option loggingEnabled to true to see if the polyfill reports something anormal.

We will extend project TestSuite to explicitly test multiple EventSource scenarii. This will take some time though.

**Comment by oparoz** [comment]
Here are a few answers:
1) 
The timeout is what actually triggers a result. So it means the script is not understanding that it got another close event and keeps the connection open until it reaches the time out value. I tried to figure out why it didn't catch the second "close" event, but couldn't. I tried to set the variable to a very short timeout value and never got a reply as the server was hammered with requests.
With 0 or null: No change

2)
Setting getArgs to undefined didn't change anything

3) 
There is nothing unusual, except the missing close
For 2 requests, to the same endpoint, using only different GET parameters
```
[eventsource]:evs cleaning up
[eventsource]:evs cleaning up
[eventsource]:Closing connection. readyState: 2
[eventsource]:evs cleaning up
```

**Comment by oparoz** [comment]
A more detailed logging
4 requests need to be made to retrieve all the data.
It starts with only 2
```
[eventsource]:evs cleaning up
[data]
[eventsource]:evs cleaning up
[data]
[eventsource]:Closing connection. readyState: 2
[eventsource]:evs cleaning up
<waiting> Not all events have been received. Callback is not called
[eventsource]:Timeout! silentTImeout:1000
[eventsource]:evs cleaning up
[data]
[eventsource]:Closing connection. readyState: 2
[eventsource]:evs cleaning up
[eventsource]:evs cleaning up
[data]
[eventsource]:evs cleaning up
[data]
[eventsource]:Closing connection. readyState: 2
[eventsource]:evs cleaning up
```
With the short timeout, I can see that it hangs twice and some requests are restarted.
All together, 6 requests are made.

**Comment by amvtek** [comment]
OK, we will extend project TestSuite so as to get the multiple stream case covered.
We will keep you posted.

**Comment by oparoz** [comment]
Thank you and if you want to test on an implementation, just install ownCloud 8 and the Gallery+ app. Thumbnails are base64 encoded and streamed back.

**Comment by oparoz** [comment]
Any progress? ;)

**Comment by amvtek** [comment]
Bonjour Olivier, we have not had the time yet to create the new
test cases that reproduce the problems you are observing. This is
on our punch list, but we can only allocate our free time to this.
Bests, AmvTek


On Tue, May 12, 2015, at 10:59 PM, Olivier Paroz wrote:
> Any progress? ;)


> — Reply to this email directly or view it on GitHub[1].

>

Web : http://www.amvtek.com/ Tel : ++40 (0)256 201 693 Skype : mvskyp



Links:

  1. https://github.com/amvtek/EventSource/issues/9#issuecomment-101403163

**Comment by amvtek** [comment]
OK, we added a test suite to attend reproducing the problem.
You may run those browsing the address : http://testevs.amvtek.com/SpecConcurrentRunner.html
Things looks OK in Firefox but not in IE11.
We now have a starting point to further investigate the issue.
Bests,
AmvTek

**Comment by oparoz** [comment]
Thanks!

**Comment by oparoz** [comment]
FYI, after having cleaned up the code by adding missing semi-colons, etc. I don't experience the issue any more. So it might be worse parsing the code with JSLint or something.

**Comment by amvtek** [comment]
What appears to matter somehow is the amount of time connections are kept open.
You may not observe any problem as a result of short duration EventSource.

We did not have the time to restart working on this, but from the tests we now have it looks that overall connection time do matter.

Bests,
AmvTek

**Comment by oparoz** [comment]
You're right, I haven't tested with longer events yet. My original problem was that connections would never close and that might simply be related to some parsing issues in IE.
